# Generated by Django 3.1.1 on 2020-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creator', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='long_description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='skill',
            name='short_description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
