# Generated by Django 3.1.1 on 2020-09-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('residence', models.CharField(max_length=64)),
                ('birthplace', models.CharField(max_length=64)),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('appearance', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('move_rate', models.IntegerField(default=0)),
                ('major_wound', models.BooleanField(default=False)),
                ('hit_points', models.IntegerField(default=0)),
                ('sanity', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('magic_points', models.IntegerField(default=0)),
                ('damage_bonus', models.IntegerField(default=0)),
                ('build', models.IntegerField(default=0)),
                ('personal_description', models.CharField(max_length=512)),
                ('ideology_and_beliefs', models.CharField(max_length=512)),
                ('significant_people', models.CharField(max_length=512)),
                ('meaningful_locations', models.CharField(max_length=512)),
                ('treasured_possessions', models.CharField(max_length=512)),
                ('traits', models.CharField(max_length=512)),
                ('injuries_and_scars', models.CharField(max_length=512)),
                ('phobias_and_manias', models.CharField(max_length=512)),
                ('arcane_tomes', models.CharField(max_length=512)),
                ('spells', models.CharField(max_length=512)),
                ('artifacts', models.CharField(max_length=512)),
                ('encounters', models.CharField(max_length=512)),
                ('spending_level', models.CharField(max_length=64)),
                ('cash', models.IntegerField(default=0)),
                ('assets', models.CharField(max_length=512)),
                ('notes', models.CharField(max_length=512)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.player')),
            ],
        ),
    ]
