# Generated by Django 3.1.1 on 2020-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200915_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_description', models.CharField(blank=True, max_length=64)),
                ('long_description', models.CharField(blank=True, max_length=256)),
                ('default_value', models.IntegerField(default=0)),
            ],
        ),
    ]
